---

filesystem_scheme: file

namespace: soc.net
protocol: tw

messages:
  atsigns_for_tweet:
    request:
      - name: tweet_id_query
        type: tweet_id_query
    response:
      - atsigns_response

targets:
  catalog:
    - name: atsigns_for_tweet_catalog_entry
      messages:
        - atsigns_for_tweet        
      title: "Twitter Conversations: AtsignsForTweet"
      tags:
        - network
        - social
        - twitter
        - pagerank
        - socialnetwork
        - ranking
        - networking
        - bigdata
        - twitter-com
        - trstrank
        - reputation
        - usergraph
        - infochimps-api
      description: >-
        Given a tweet id, get back all the tweets that are retweets or replies of it.
        
types:

  - name: tweet_id_query
    type: record
    fields:
      - name: tweet_id
        type: long
        doc: A twitter tweet id
        
  - name: atsigns_response
    fields:
      - name: total
        type: int
        doc: total number of tweets that are replies or retweets of the tweet id queried
      - name: tweet_id
        type: int
        doc: the tweet id used as the query
      - name: tweet_ids
        type: array
        items: long
        doc: An array of tweet ids
        
