---
:db_location: "https://developers-zone.digitalenvoy.net/downloads/db"
:user_pass: "kelly.josephc@infochimps.org:#rdsf8se"
:features:
  :geo: 3
  :edge: 4
  :sic: 5
  :domain: 6
  :zip_area_time: 7
  :isp: 8
  :home_business: 9
  :asn: 10
  :language: 11
  :proxy: 12
  :org_name: 13
  :is_an_isp: 14
  :company: 15
  :demographics: 17
  :naics: 18

# We ARE licensed for (4,6,7,8,10,11,12,15,17,18)
:not_licensed_for:
  - na_14
  - na_13
  - na_09
  - na_05
  - na_03
  
:skip_features:
  - na_04
  - na_06
  - na_07
  - na_08
  - na_10
  - na_11
  - na_15
  - na_17
  - na_18

:feature_keys:
  na_03: geo
  na_06: domain
  na_07: zip_area_time
  na_08: isp
  na_11: language
  na_12: proxy
  na_15: company
  na_17: demographics
  na_18: naics
  na_04: edge
  
:feature_names:
  na_03: Geographical Locations
  na_06: Web Domains
  na_07: ZIP codes, area codes, and time zones
  na_08: Internet Service Providers (ISPs)
  na_11: Primary &amp; secondary languages spoken
  na_12: Proxy servers
  na_15: Companies
  na_17: Demographics
  na_18: NAICS Industry Codes
  na_04: Accurate Geographical Locations  

na_12:
  - start_ip
  - end_ip
  - name: proxy_type
    datatype: string
    description: |-
      The type of "proxy server":http://en.wikipedia.org/wiki/Proxy_server running at the IP.  Possible values are
      ** @?@ - not determined to a proxy
      ** @anonymous@ - Actual IP address of client is not available
      ** @transparent@ - Actual IP address of client is available via HTTP headers
      ** @aol@ - AOL proxy
      ** @corporate@ - Multiple users proxied from a corporate network and clients "share" one  apparent address
      ** @public@ - Multiple users proxied from a location that allows public access to the Internet
      ** @edu@ - Proxied users from an educational institution
na_04:
  - start_ip
  - end_ip
  - name: edge_country
    datatype: string
    description: ~
  - name: edge_region
    datatype: string
    description: ~
  - name: edge_city
    datatype: string
    description: ~
  - name: edge_conn_speed
    datatype: string
    description: ~
  - name: edge_metro_code
    datatype: integer
    description: ~
  - name: edge_latitude
    datatype: float
    description: ~
  - name: edge_longitude
    datatype: float
    description: ~
  - name: edge_postal_code
    datatype: string
    description: ~
  - name: edge_country_code
    datatype: integer
    description: ~
  - name: edge_region_code
    datatype: integer
    description: ~
  - name: edge_city_code
    datatype: integer
    description: ~
  - name: edge_continent_code
    datatype: integer
    description: ~
  - name: edge_two_letter_country
    datatype: string
    description: ~
  - name: edge_internal_code
    datatype: integer
    description: ~
    
na_07:
  - start_ip
  - end_ip
  - name: area_code
    datatype: integer
    description: 3-digit US telephone area code.
  - name: zip_code_ignored
    datatype: integer
    ignored: true
    description: ~
  - name: gmt_offset
    datatype: integer
    description: "Time zone GMT/UTC offset (+hhmm)"
  - name: in_dst
    datatype: string
    description: Are they currently observering DST?
  - name: zip
    datatype: string
    description: ZIP code, where available.
  - name: zip_country
    datatype: string
    description: 3-letter country code.
    
na_08:
  - start_ip
  - end_ip
  - name: isp
    datatype: string
    description: ISP owning IP address.

na_06:
  - start_ip
  - end_ip
  - name: domain
    datatype: string
    description: Domain served from IP address.

na_15:
  - start_ip
  - end_ip
  - name: company
    datatype: string
    description: Company registered for IP address.

na_17:
  - start_ip
  - end_ip
  - name: rank
    datatype: integer
    description: ~
  - name: households
    datatype: integer
    description: Households (in thousands)
  - name: women
    datatype: integer
    description: Women (in thousands)
  - name: w18_34
    datatype: integer
    description: Women, ages 18 - 34 (in thousands)
  - name: w35_49
    datatype: integer
    description: Women, ages 35 - 49 (in thousands)
  - name: men
    datatype: integer
    description: Men (in thousands)
  - name: m18_34
    datatype: integer
    description: Men, ages 18 - 34 (in thousands)
  - name: m35_49
    datatype: integer
    description: Men, ages 35 - 49 (in thousands)
  - name: teens
    datatype: integer
    description: Children, ages 13-17 (in thousands)
  - name: kids
    datatype: integer
    description: Children 12 and under (in thousands)
    
na_03:
  - start_ip
  - end_ip
  - name: country
    datatype: string
    description: 3-letter country name
  - name: region
    datatype: string
    description: Region name ("@no region@" when country lacks regions)
  - name: city
    datatype: string
    description: City name
  - name: conn_speed
    datatype: string
    description: |-
      The connection speed of the IP.  Possible values include
      ** @?@
      ** @dialup@
      ** @broadband@
      ** @cable@
      ** @xdsl@
      ** @mobile@
      ** @t1@
      ** @t3@
      ** @oc3@
      ** @oc12@
      ** @satellite@
      ** @wireless@
  - name: country_conf
    datatype: integer
    description: Confidence in assignment of country
  - name: region_conf
    datatype: integer
    description: Confidence in assignment of region
  - name: city_conf
    datatype: integer
    description: Confidence in assignment of city
  - name: metro_code
    datatype: integer
    description: |-
      Digital Envoy metro code.   Metros are regions larger than cities that may cross state lines.  In the US, metro codes are based on "Designated Market Areas":http://en.wikipedia.org/wiki/Media_market (DMAs).  In the UK, metro codes are based on "ITV regions":http://en.wikipedia.org/wiki/ITV. Cities not in any particular metro are a "@0@".  Cities that have not yet had an appropriate metroization standard applied are a "@-1@".
  - name: lat
    datatype: float
    description: Latitude
  - name: longitude
    datatype: float
    description: Longitude
  - name: country_code
    datatype: integer
    description: Digital Envoy country code
  - name: region_code
    datatype: integer
    description: Digital Envoy region code
  - name: city_code
    datatype: integer
    description: Digital Envoy city code
  - name: continent_code
    datatype: integer
    description: |-
      Digital Envoy continent code.  Possible values are
      ** 0 - No continent
      ** 1 - Africa
      ** 2 - Antarctica
      ** 3 - Australia
      ** 4 - Asia
      ** 5 - Europe
      ** 6 - North America
      ** 7 - South America
      
  - name: two_letter_country
    datatype: string
    description: 2-letter country name

na_18:
  - start_ip
  - end_ip
  - name: naics_code
    datatype: integer
    description: |-
      "NAICS":http://www.census.gov/naics industry code for company operating at IP

na_11:
  - start_ip
  - end_ip
  - name: lang
    datatype: string
    description: Primary language spoken at IP
  - name: second_langs
    datatype: string
    description: Comma-separated list of secondary languages spoken at IP

na_05:
  - start_ip
  - end_ip
  - name: sic_code
    datatype: integer
    description: ~

na_09:
  - start_ip
  - end_ip
  - name: homebiz_type
    datatype: string
    description: ~
