
#
# You will also need to create a config/private.yaml file containing secrets
# such as your twitter authentication (if you will be gathering data from
# twitter), etc.  See the file 'config/private-sample.yaml'.
#


# Directory for data.  Create this directory and then run './bin/imw-scaffold'
# to instantiate and create the links.
- :data_dir:    ~/data

