---

hadoop:
  hdfs: ip-10-116-226-88.ec2.internal
  reduce_tasks: 232
  pig_classpath: /usr/lib/hbase/lib/jline-0.9.94.jar:/usr/lib/hbase/lib/guava-r05.jar:/usr/lib/hbase/lib/commons-lang-2.5.jar:/usr/lib/hbase/hbase.jar:/usr/lib/hbase/hbase-tests.jar:/usr/local/share/pig/pig.jar
  pig_options: "-Dmapred.min.split.size=50000000  -Dmapred.map.max.attempts=100 -Dmapred.reduce.max.attempts=100 -Dmapred.max.tracker.failures=100 -Dmapred.map.tasks.speculative.execution=false"
  pig_home: /usr/local/share/pig
  
hbase:
  twitter_users_table: soc_net_tw_twitter_user
  twitter_users_cf: info
  twitter_rel_table: soc_net_tw_a_rel_b  
  jars:
    - /home/travis/dev/HbaseBulkloader/build/hbase_bulkloader.jar
    - /usr/lib/hbase/lib/jline-0.9.94.jar
    - /usr/lib/hbase/lib/guava-r05.jar
    - /usr/lib/hbase/hbase.jar
    - /usr/lib/hbase/lib/zookeeper.jar

trstrank:
  iterations: 10
  damping: 0.85f
  final_resting_place_in_the_cloud: s3n://infochimps-data/data/sn/tw/fixd/graph/trstrank
  
workflow:
  id: 20110301
  s3_graph_dir: s3://s3hdfs.infinitemonkeys.info/data/sn/tw/fixd/graph

  
filesystem_scheme: hdfs

namespace: social.network.tw
protocol: influence

types:
