---

# hadoop stuff
hdfs: ip-10-117-77-123.ec2.internal
hadoop_reduce_tasks: 15
#

# generic workflow stuff
flow_id: 20110215
namespace: /soc/net/tw
protocol: people_search
filesystem_scheme: hdfs
#

pig_classpath: /usr/lib/hbase/lib/jline-0.9.94.jar:/usr/lib/hbase/lib/guava-r05.jar:/usr/lib/hbase/lib/commons-lang-2.5.jar:/usr/lib/hbase/hbase.jar:/usr/lib/hbase/hbase-tests.jar:/usr/local/share/pig/pig.jar
pig_options: '-Dmapred.min.split.size=5000000000 -Dmapred.task.timeout=1800000'
es_jars:
  - /home/jacob/Programming/wonderdog/build/wonderdog.jar
  - /usr/local/share/elasticsearch/lib/elasticsearch-0.14.2.jar
  - /usr/local/share/elasticsearch/lib/jline-0.9.94.jar
  - /usr/local/share/elasticsearch/lib/jna-3.2.7.jar
  - /usr/local/share/elasticsearch/lib/log4j-1.2.15.jar
  - /usr/local/share/elasticsearch/lib/lucene-analyzers-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-core-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-fast-vector-highlighter-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-highlighter-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-memory-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-queries-3.0.3.jar
hbase_jars:
  - /home/jacob/Programming/hbase_bulkloader/build/hbase_bulkloader.jar
  - /usr/lib/hbase/lib/jline-0.9.94.jar
  - /usr/lib/hbase/lib/guava-r05.jar
  - /usr/lib/hbase/hbase.jar
  - /usr/lib/hbase/lib/zookeeper.jar
hbase_table: soc_net_tw_twitter_user
hbase_column_family: profile
es_index: soc_net_tw_twitter_user
es_obj_type: profile
bulk_size: 500
twitter_user_profile:
  - name: user_id
    pig_type: int
  - name: scraped_at
    pig_type: long
  - name: screen_name
    pig_type: chararray
  - name: name
    pig_type: chararray
  - name: url
    pig_type: chararray
  - name: location
    pig_type: chararray
  - name: description
    pig_type: chararray
  - name: time_zone
    pig_type: chararray
  - name: utc_offset
    pig_type: chararray
  - name: lang
    pig_type: chararray
  - name: geo_enabled
    pig_type: chararray
  - name: verified
    pig_type: chararray
  - name: contributors_enabled
    pig_type: chararray
