---
namespace: /soc/net/tw
protocol: people_search
filesystem_scheme: hdfs
es_jars:
  - /home/jacob/Programming/wonderdog/build/wonderdog.jar
  - /usr/local/share/elasticsearch/lib/elasticsearch-0.14.2.jar
  - /usr/local/share/elasticsearch/lib/jline-0.9.94.jar
  - /usr/local/share/elasticsearch/lib/jna-3.2.7.jar
  - /usr/local/share/elasticsearch/lib/log4j-1.2.15.jar
  - /usr/local/share/elasticsearch/lib/lucene-analyzers-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-core-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-fast-vector-highlighter-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-highlighter-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-memory-3.0.3.jar
  - /usr/local/share/elasticsearch/lib/lucene-queries-3.0.3.jar
hbase_jars:
  - /home/jacob/Programming/hbase_bulkloader/build/hbase_bulkloader.jar
  - /usr/lib/hbase/lib/jline-0.9.94.jar
  - /usr/lib/hbase/lib/guava-r05.jar
  - /usr/lib/hbase/hbase.jar
  - /usr/lib/hbase/lib/zookeeper.jar
hbase_table: soc_net_tw_twitter_user
hbase_column_family: profile
flow_id: 20110215
